
name: Build and publish

on:
  push:
    tags:
       - 'v*'
       - 'dev-*'

permissions:
  contents: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Determine web ref
        id: web-ref
        run: |
          if [[ "$GITHUB_REF_NAME" == dev-* ]]; then
            echo "ref=dev" >> "$GITHUB_OUTPUT"
          else
            echo "ref=" >> "$GITHUB_OUTPUT"
          fi
      - name: Checkout Web
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: cernbox/web
          ref: ${{ steps.web-ref.outputs.ref }}
          path: web
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Install node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
      - name: Set web package version
        working-directory: web
        run: |
          if [[ "$GITHUB_REF_NAME" == v* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="$GITHUB_REF_NAME"
          fi
          npm pkg set version="$VERSION"
      - name: Build Web
        run: |
          export TITLE=CERNBox
          export SOURCE_MAP=true
          export REQUIRE_TIMEOUT=20
          export DOCUMENTATION_URL="https://cernbox.docs.cern.ch/web/#desktop-requirements"

          cd web
          make dist
      - name: Create release
        run: |
          mkdir -p release
          tar -C web/dist -czf release/web.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: ${{ startsWith(github.ref_name, 'dev-') }}
          files: release/web.tar.gz
      - name: Create tag in web repo
        if: startsWith(github.ref_name, 'v')
        run: |
          cd web
          git tag ${GITHUB_REF/refs\/tags\//}
          git push --tags
