
name: Build and publish

on:
  push:
    tags:
       - 'v*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web
        uses: actions/checkout@v3
        with:
          repository: cernbox/web
          path: web
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
      - name: Build Web
        run: |
          export TITLE=CERNBox
          export SOURCE_MAP=true
          export REQUIRE_TIMEOUT=20
          export DOCUMENTATION_URL="https://cernbox.docs.cern.ch/web/#desktop-requirements"

          cd web
          make dist
      - name: Create release
        run: |
          mkdir -p release
          tar -C web/dist -czf release/web.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: release/web.tar.gz
      - name: Create tag in web repo
        run: |
          cd web
          git tag ${GITHUB_REF/refs\/tags\//}
          git push --tags
